from __future__ import annotations

import unittest
from unittest.mock import patch

from aviation_rag.config import Settings
from aviation_rag.phase3_hoang_grounded_qa import Phase3HoangGroundedQA
from aviation_rag.schemas import MiddleAgentOutput, RetrievedDoc


class OutputAgentFallbackTests(unittest.TestCase):
    def test_fallback_when_route_llm_call_fails(self):
        settings = Settings(route_llm_api_key="fake-key")
        phase3 = Phase3HoangGroundedQA(settings)
        phase2_output = MiddleAgentOutput(
            query_id="q_test_1",
            predicted_intent="Technical_Procedure",
            topk_docs=[
                RetrievedDoc(
                    doc_id="doc_E1",
                    chunk_id="doc_E1#0",
                    chunk_text="Engine warning checklist and maintenance procedure text.",
                    scores={"bm25": 0.6, "semantic": 0.5, "final": 0.56},
                    metadata={},
                )
            ],
            retrieval_diagnostics={},
        )

        with patch.object(phase3, "_call_route_llm", side_effect=RuntimeError("network down")):
            output = phase3.generate(
                question="engine warning checklist",
                middle_output=phase2_output,
                allow_fallback=True,
            )

        self.assertEqual(output.query_id, "q_test_1")
        self.assertTrue(len(output.answer) > 0)
        self.assertTrue(len(output.citations) > 0)

    def test_route_llm_tries_next_model_after_one_retry(self):
        settings = Settings(
            route_llm_api_key="fake-key",
            route_llm_models=("bad/model:free", "good/model:free"),
        )
        phase3 = Phase3HoangGroundedQA(settings)
        phase2_output = MiddleAgentOutput(
            query_id="q_test_2",
            predicted_intent="Incident_Report",
            topk_docs=[
                RetrievedDoc(
                    doc_id="doc_A1",
                    chunk_id="doc_A1#0",
                    chunk_text="Engine failure after takeoff with emergency return.",
                    scores={"bm25": 0.6, "semantic": 0.5, "final": 0.56},
                    metadata={},
                )
            ],
            retrieval_diagnostics={},
        )
        calls = []

        def fake_model_call(*, model, question, context_block, doc_ids):
            calls.append(model)
            if model == "bad/model:free":
                raise RuntimeError("rate limited")
            return {
                "answer": "Supported by doc_A1.",
                "citation_doc_ids": ["doc_A1"],
                "grounding_notes": "Generated by test route model.",
                "route_llm_model": model,
            }

        with patch.object(phase3, "_call_route_llm_model", side_effect=fake_model_call):
            output = phase3.generate(
                question="engine failure",
                middle_output=phase2_output,
                allow_fallback=False,
            )

        self.assertEqual(calls, ["bad/model:free", "bad/model:free", "good/model:free"])
        self.assertIn("Supported by doc_A1", output.answer)
        self.assertEqual(output.grounding_report.get("route_llm_model"), "good/model:free")


if __name__ == "__main__":
    unittest.main()
