from __future__ import annotations

import json
import re
import urllib.error
import urllib.request
from pathlib import Path
from typing import Dict, List, Tuple

from .cancel import raise_if_cancelled
from .config import Settings
from .io_utils import append_jsonl
from .schemas import Citation, FinalOutput, MiddleAgentOutput

TOKEN_RE = re.compile(r"[a-z0-9]+")
JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)


def _tokenize(text: str) -> set[str]:
    return set(TOKEN_RE.findall((text or "").lower()))


def _clean_snippet(text: str, max_chars: int = 280) -> str:
    snippet = re.sub(r"\s+", " ", text or "").strip()
    if len(snippet) > max_chars:
        snippet = snippet[: max_chars - 3].rstrip() + "..."
    return snippet


class Phase3HoangGroundedQA:
    def __init__(self, settings: Settings):
        self.settings = settings
        self.last_route_attempts: list[dict[str, object]] = []

    def _build_context(self, middle_output: MiddleAgentOutput) -> Tuple[str, List[str]]:
        lines: List[str] = []
        doc_ids: List[str] = []
        for index, doc in enumerate(middle_output.topk_docs, start=1):
            lines.append(f"[{index}] doc_id={doc.doc_id} chunk_id={doc.chunk_id}\n{doc.chunk_text}\n")
            doc_ids.append(doc.doc_id)
        return "\n".join(lines), doc_ids

    def _messages(self, question: str, context_block: str, doc_ids: List[str]) -> list[dict[str, str]]:
        return [
            {
                "role": "system",
                "content": (
                    "You are Hoang's aviation grounded QA agent. "
                    "Answer only with evidence from context. "
                    "Return compact JSON with keys: answer, citation_doc_ids, grounding_notes. "
                    "Use only doc ids from the allowed list."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Question:\n{question}\n\n"
                    f"Context:\n{context_block}\n\n"
                    f"Allowed doc ids: {doc_ids}\n\n"
                    "Respond as JSON only."
                ),
            },
        ]

    def _parse_route_response(self, content: str, doc_ids: list[str], model: str) -> Dict[str, object]:
        payload = None
        try:
            payload = json.loads(content)
        except Exception:
            match = JSON_BLOCK_RE.search(content)
            if match:
                try:
                    payload = json.loads(match.group(0))
                except Exception:
                    payload = None
        if isinstance(payload, dict):
            payload.setdefault("citation_doc_ids", doc_ids[:2])
            payload.setdefault("grounding_notes", f"Generated by {model} through OpenRouter.")
            payload["route_llm_model"] = model
            return payload
        return {
            "answer": str(content),
            "citation_doc_ids": doc_ids[:2],
            "grounding_notes": f"Fallback parse used because {model} did not return valid JSON.",
            "route_llm_model": model,
        }

    def _call_route_llm_model(
        self,
        *,
        model: str,
        question: str,
        context_block: str,
        doc_ids: List[str],
        cancel_event: object | None = None,
    ) -> Dict[str, object]:
        raise_if_cancelled(cancel_event)
        if not self.settings.route_llm_api_key:
            raise ValueError("OPENROUTER_API_KEY is missing. Route LLM generation requires it.")
        url = f"{self.settings.route_llm_base_url}/chat/completions"
        body = {
            "model": model,
            "messages": self._messages(question, context_block, doc_ids),
            "temperature": self.settings.route_llm_temperature,
            "max_tokens": self.settings.route_llm_max_tokens,
            "stream": False,
        }
        request = urllib.request.Request(
            url,
            data=json.dumps(body).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.settings.route_llm_api_key}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost:8501",
                "X-Title": "Aviation Safety RAG",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.settings.route_llm_timeout_seconds) as response:
                raw = response.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"OpenRouter HTTP {exc.code}: {detail[:500]}") from exc
        except urllib.error.URLError as exc:
            raise RuntimeError(f"OpenRouter network error: {exc.reason}") from exc

        raise_if_cancelled(cancel_event)
        payload = json.loads(raw)
        if payload.get("error"):
            raise RuntimeError(f"OpenRouter response error: {payload['error']}")
        choices = payload.get("choices") or []
        if not choices:
            raise RuntimeError("OpenRouter response did not include choices.")
        message = choices[0].get("message") or {}
        content = str(message.get("content") or "").strip()
        if not content:
            raise RuntimeError("OpenRouter response content was empty.")
        parsed = self._parse_route_response(content, doc_ids, model)
        parsed["route_llm_raw_model"] = payload.get("model", model)
        return parsed

    def _call_route_llm(
        self,
        question: str,
        context_block: str,
        doc_ids: List[str],
        cancel_event: object | None = None,
    ) -> Dict[str, object]:
        self.last_route_attempts = []
        if not self.settings.route_llm_models:
            raise ValueError("OPENROUTER_MODELS is empty. Add at least one Route LLM model.")
        for model in self.settings.route_llm_models:
            for attempt in range(1, 3):
                raise_if_cancelled(cancel_event)
                try:
                    try:
                        payload = self._call_route_llm_model(
                            model=model,
                            question=question,
                            context_block=context_block,
                            doc_ids=doc_ids,
                            cancel_event=cancel_event,
                        )
                    except TypeError as exc:
                        if "cancel_event" not in str(exc):
                            raise
                        payload = self._call_route_llm_model(
                            model=model,
                            question=question,
                            context_block=context_block,
                            doc_ids=doc_ids,
                        )
                    self.last_route_attempts.append({"model": model, "attempt": attempt, "status": "ok"})
                    return payload
                except Exception as exc:
                    self.last_route_attempts.append(
                        {
                            "model": model,
                            "attempt": attempt,
                            "status": "failed",
                            "error": str(exc)[:240],
                        }
                    )
            # One retry failed: do not use this model again in the current request.
        raise RuntimeError("All OpenRouter models failed after one retry each.")

    def _fallback_answer(self, question: str, middle_output: MiddleAgentOutput) -> Dict[str, object]:
        evidence_lines = []
        for index, doc in enumerate(middle_output.topk_docs[:3], start=1):
            evidence_lines.append(f"{index}. Document {doc.doc_id}: {_clean_snippet(doc.chunk_text)}")
        if evidence_lines:
            answer = "\n".join(
                [
                    "Local grounded fallback: Route LLM is not configured, unavailable, or Fast local mode is active.",
                    f"Query: {question}",
                    "",
                    "Evidence highlights:",
                    *evidence_lines,
                    "",
                    "Review the Evidence tab before treating this as a supported research answer.",
                ]
            )
        else:
            answer = (
                "Local grounded fallback could not find retrieved evidence for this query. "
                "Try a more specific aviation incident, hazard, maintenance item, or airport condition."
            )
            return {
                "answer": answer,
                "citation_doc_ids": [],
                "grounding_notes": "Local fallback mode used by Hoang phase 3.",
            }
        return {
            "answer": answer,
            "citation_doc_ids": [doc.doc_id for doc in middle_output.topk_docs[:3]],
            "grounding_notes": "Local fallback mode used by Hoang phase 3.",
        }

    def _grounding_metrics(self, answer: str, contexts: List[str]) -> Dict[str, float]:
        answer_tokens = _tokenize(answer)
        context_tokens = _tokenize(" ".join(contexts))
        overlap_ratio = 0.0
        if answer_tokens:
            overlap_ratio = len(answer_tokens.intersection(context_tokens)) / len(answer_tokens)
        return {
            "overlap_ratio": overlap_ratio,
            "hallucination_risk": max(0.0, min(1.0, 1.0 - overlap_ratio)),
        }

    def generate(
        self,
        question: str,
        middle_output: MiddleAgentOutput,
        allow_fallback: bool = True,
        force_local: bool = False,
        cancel_event: object | None = None,
    ) -> FinalOutput:
        raise_if_cancelled(cancel_event)
        context_block, doc_ids = self._build_context(middle_output)
        if force_local:
            payload = self._fallback_answer(question, middle_output)
        elif self.settings.route_llm_api_key:
            try:
                payload = self._call_route_llm(question, context_block, doc_ids, cancel_event=cancel_event)
            except Exception:
                raise_if_cancelled(cancel_event)
                if allow_fallback:
                    payload = self._fallback_answer(question, middle_output)
                else:
                    raise
        elif allow_fallback:
            payload = self._fallback_answer(question, middle_output)
        else:
            raise ValueError("OPENROUTER_API_KEY is missing and fallback is disabled.")

        raise_if_cancelled(cancel_event)
        citations = [
            Citation(doc_id=doc_id, reason="Phase 3 cited this document")
            for doc_id in payload.get("citation_doc_ids", [])[:5]
        ]
        if not citations:
            citations = [
                Citation(doc_id=doc.doc_id, reason="Fallback to top-ranked evidence")
                for doc in middle_output.topk_docs[:2]
            ]

        metrics = self._grounding_metrics(
            answer=str(payload.get("answer", "")),
            contexts=[doc.chunk_text for doc in middle_output.topk_docs],
        )
        report = {
            "grounding_notes": str(payload.get("grounding_notes", "")),
            "overlap_ratio": metrics["overlap_ratio"],
            "retrieval_docs_considered": len(middle_output.topk_docs),
            "route_llm_model": payload.get("route_llm_model"),
            "route_llm_raw_model": payload.get("route_llm_raw_model"),
            "route_llm_attempts": self.last_route_attempts,
        }
        return FinalOutput(
            query_id=middle_output.query_id,
            query_raw=question,
            answer=str(payload.get("answer", "")),
            citations=citations,
            hallucination_risk=metrics["hallucination_risk"],
            grounding_report=report,
        )

    def write_output(self, output: FinalOutput, path: Path | None = None) -> Path:
        target = path or self.settings.phase3_output_path
        append_jsonl(target, output)
        return target
